### ISSUE TITLE
MacOS 바이너리를 받아서 사용해볼려고 하는데요. 사용할 수 없는 바이너리라고 실행이 되지 않습니다. 

### ISSUE THREAD

**Issue by easylogic** [suhdonghwi/nuri#12]
혹시 맥에서 어떻게 실행해야하는지 가이드가 있을가요?

**Comment by suhdonghwi** [comment]
혹시 알려지지 않은 개발자의 프로그램은 실행할 수 없다, 이런 맥락의 오류가 발생하시나요?

**Comment by easylogic** [comment]
넵 맞습니다. 그런 메세지였습니다.

**Comment by suhdonghwi** [comment]
애플이 개발자 프로그램 등록하고 인증서를 안하면 그렇게 처리하더라구요... 번거롭지만 다음과 같이 해주셔야 실행이 가능합니다.

1. 터미널에서 `./nuri` 로 실행
2. 에러가 발생하면 "시스템 환경설정 -> 보안 및 개인 정보 보호 -> 확인 없이 열기 버튼 클릭"

이걸 nuri와 haneul에 대해서 해주시면 됩니다.

**Comment by easylogic** [comment]
실행 권한은 해결이 되었습니다.  실제로 실행을 하면 아래와 같이 나옵니다. 

```sh
# ./nuri ./유용한\ 함수들.nuri 

RPython traceback:
  File "implement.c", line 297, in entry_point
  File "rpython_rlib.c", line 475, in open__str
Fatal RPython error: OSError
nuri: callCommand: ./haneul ./유용한 함수들.hn (exit -6): failed

```

**Comment by suhdonghwi** [comment]
아.. 지금 그 파일 이름에 공백이 있는 파일은 실행하면 문제가 발생하네요 ㅠㅠㅠㅠ 죄송합니다 파일을 실행할 때 파일 이름을 공백 없이 바꿔주시면 감사하겠습니다.

이 문제는 고치도록 하겠습니다.

**Comment by easylogic** [comment]
@suhdonghwi  

이름을 바꾼 이후에 실행은 가능한데 아무것도 표시가 안되는 것 같습니다.  

원래 표시가 안되는게 맞는건가요?  

혹시 화면에 출력해주는 다른 예제가 있을까요?

**Comment by suhdonghwi** [comment]
넵! `유용한 함수.nuri`는 원래 함수만 정의하는 것이라 출력이 없는게 맞습니다. 출력을 하는 다른 예제들은 https://github.com/suhdonghwi/nuri/tree/master/examples 여기에서 찾아보실 수 있습니다!

만약 예제를 실행하는데 함수를 찾을 수 없다는 에러가 뜬다면 코드 맨 윗 줄에

```
꾸러미 "유용한 함수들.nuri"
```

을 추가해주세요 :) (해당 코드와 같은 경로에 `유용한 함수들.nuri`이 있어야합니다)

**Comment by easylogic** [comment]
아하 ~ 성공했습니다.  꾸러미 가  다른 언어 import 같은 개념이군요.

**Comment by suhdonghwi** [comment]
맞습니다!! 프로젝트에 관심 가져주셔서 감사합니다 👍
