### ISSUE TITLE
구조체 이름과 필드에  영어문법을 지원할 계획이 있으신가요? 

### ISSUE THREAD

**Issue by easylogic** [suhdonghwi/nuri#13]
간단하게 RGB 출력코드를 만들어봤는데요.  

색의 경우 보통 RGB 형태로 사용하는데요.
한글로만 쓰니깐 뭔가 단어가 많이 어색한 느낌이 드는 것 같습니다. 
혹시 구조체에 영문 이름도 지원하실 계획이 있는지 궁금하네요. 

```js
구조체 색: 빨강, 초록, 파랑

상수 [나의색]: 색(빨강: 255, 초록: 255, 파랑: 30)

함수 [알지비]의 거리:
  [알지비]의 빨강 * [알지비]의 초록 * [알지비]의 파랑

([나의색]의 거리)를 출력하다
```

**Comment by suhdonghwi** [comment]
기술적으로 안되는 부분은 아니라서 충분히 가능할 것 같습니다 :) 이 부분도 추가해보겠습니다 감사합니다!
