### ISSUE TITLE
품사 체커 추가

### ISSUE THREAD

**Issue by suhdonghwi** [suhdonghwi/nuri#16]
현재 함수 연쇄 호출 활용은, 동사로 선언되지 않아도 함수의 이름이 `~다`로 끝나기만 하면 가능합니다. 극단적인 예시이긴 하지만 `함수 바다`를 선언해도 `바고`라는 활용이 된다는 뜻입니다. 이를 방지하기 위해서 다른 언어의 type checker에 해당하는 품사 체커를 만들 필요성이 있습니다.

**Comment by Dongyeongkim** [comment]
품사체킹을 Konlpy(https://github.com/konlpy/konlpy)의 품사체커를 활용해서 작성하면 좋을 듯 합니다!

**Comment by suhdonghwi** [comment]
의견 감사합니다! 그런데 하스켈 바인딩이 없어서.. ㅠㅠ 쓰려면 직접 구현해야겠어요.
