### ISSUE TITLE
보여주다 -> 보여준다

### ISSUE THREAD

**Issue by gomjellie** [suhdonghwi/nuri#21]
연결하다 -> 연결한다 
~와 ~를 더하다 -> ~와 ~를 더한다
~을 보여주다 -> ~을 보여준다
출력하다 -> 출력한다

이런식으로 쓰는게 더 자연스럽게 읽히는데 저런 표현은 혹시 구현하는게 어려울까요?

**Comment by suhdonghwi** [comment]
안녕하세요! 우선 이슈 올려주셔서 감사합니다 👍

사실 이 부분은 처음에 고민을 했었던 부분인데요, (`~하다`로 할지 `~한다`로 할지) 아무래도 `~고` 활용을 할 때 `보여준고`가 아닌 `보여주고` 처럼 되기 때문에 나름의 일관성을 유지하기 위해서 `~하다`로 선택을 했습니다.

두 방안 모두 지원하는 방향은 생각해보도록 하겠습니다. 감사합니다!

**Comment by gomjellie** [comment]
이미 고민했던 문제였군요. 멋진 프로젝트 응원합니다!
