### ISSUE TITLE
유용한 함수들 꾸러미 목록으로 보여주다 함수 에러

### ISSUE THREAD

**Issue by CraftyDragon678** [suhdonghwi/nuri#27]
이전 커밋(790fa5493b22ba870f04c29a4a4c0ce8778cdd1e)에서 함수 `출력하다`의 이름이 `보여주다`로 바뀌었는데,
"유용한 함수들"에 있는 목록으로 보여주다 함수에서 `~를 출력하다`함수를 사용합니다.

또 쉼표는 같은줄에 보여주는 게 깔끔할 것 같습니다

그래서 아래 처럼 수정이 필요해 보입니다.
```
# 목록의 원소를 콤마로 나누어서 출력합니다.
동사 [목록]을 목록으로 보여주다:
  만약 [목록] == {} 이라면 없음
  아니라면 만약 [목록]의 나머지 == {} 이라면 ([목록]의 첫번째)를 보여주다
  아니라면 순서대로
    ([목록]의 첫번째)를 같은줄에 보여주다
    ", "를 같은줄에 문자열로 보여주다
    ([목록]의 나머지)를 목록으로 보여주다
```

또한 문법 문서와 README.md에 함수 `출력하다`를 사용하는데 헷갈릴 수 있어서 `보여주다`로 바꾸어야할 것 같습니다.

**Comment by suhdonghwi** [comment]
예리하시네요! 지적 감사합니다 조만간 수정하겠습니다..!
