### ISSUE TITLE
설치 방법을 보여주었으면 좋을 거 같습니다

### ISSUE THREAD

**Issue by AkiaCode** [suhdonghwi/nuri#29]
지금 보니까 문법 설명이랑 예제들 밖에 없어서 처음 보는 유저들이 어떻게 `설치/실행`해야 할지 잘 모르는 경우가 생기는 거 같습니다

**Comment by suhdonghwi** [comment]
설치 링크 및 사용 방법은 [누리 사용해보기 문서](https://github.com/suhdonghwi/nuri/blob/master/USAGE.md)에 적어두었습니다 :) 혹시 부족한 부분이 있다면 말씀해주세요!

**Comment by AkiaCode** [comment]
아하, 저가 미쳐 못 봤던 거군요;;

**Comment by AkiaCode** [comment]
그 리드미에서는 안보여서 찾기 어려운 거였군요;;
