### ISSUE TITLE
C-style 함수 호출 인자 배정 방식

### ISSUE THREAD

**Issue by CraftyDragon678** [suhdonghwi/nuri#30]
https://github.com/suhdonghwi/nuri/blob/master/docs/grammar.md#c-style-%ED%95%A8%EC%88%98-%ED%98%B8%EC%B6%9C

C-style 함수 호출 방식과 관련한 문서에서는 가장 앞에 있는 인자부터 배정이 된다고 하지만, 아래 함수로 테스트 할 경우, `1 2 3 4`가 아닌 `4 3 2 1`이 출력됩니다.

```
함수 [ㄱ]과 [ㄴ]의 [ㄷ]에 [ㄹ]을 테스트하다:
  순서대로
    [ㄱ]을 보여주다
    [ㄴ]을 보여주다
    [ㄷ]을 보여주다
    [ㄹ]을 보여주다

테스트하다(1, 2, 3, 4)
```

**Comment by suhdonghwi** [comment]
main 브랜치에 관련 내용 수정 커밋을 올렸는데, 혹시 다시 테스트 해보실 수 있나요?

**Comment by CraftyDragon678** [comment]
네! 의도대로 작동되네요 감사합니다 :)
